### ISSUE TITLE
Uncaught ReferenceError: ms is not defined throws at components/c/TestStopWatch.js:63:32

### ISSUE THREAD

**Issue by shaikrizwan** [moshekarmel1/Stopwatch#1]
({
	doInit : function(component, event, helper) {

	},
    doScriptLoad : function(component, event, helper) {

	},
    onClick : function(component, event, helper) {
        var div = component.find("time").getElement();
        var id = event.target.id;
        var	clsStopwatch = function() {
            // Private vars
            var	startAt	= startAt || 0;	// Time of last start / resume. (0 if not running)
            var	lapTime	= lapTime || 0;	// Time on the clock when last stopped in milliseconds

            var	now	= function() {
                return (new Date()).getTime();
            };

            // Public methods
            // Start or resume
            this.start = function() {
                startAt	= startAt ? startAt : now();
            };

            // Stop or pause
            this.stop = function() {
                // If running, update elapsed time otherwise keep it
                lapTime	= startAt ? lapTime + now() - startAt : lapTime;
                startAt	= 0; // Paused
            };

            // Reset
            this.reset = function() {
                lapTime = startAt = 0;
            };

            // Duration
            this.time = function() {
                return lapTime + (startAt ? now() - startAt : 0);
            };
        };

        var stopwatch = component.get("v.stopwatch");
        var x = stopwatch || new clsStopwatch();
        if(!stopwatch){
        	component.set("v.stopwatch", x);
        }

        function pad(num, size) {
            var s = "0000" + num;
            return s.substr(s.length - size);
        }

        function formatTime(time) {
            var h = m = s = ms = 0;
            var newTime = '0';

            h = Math.floor( time / (60 * 60 * 1000) );
            time = time % (60 * 60 * 1000);
            m = Math.floor( time / (60 * 1000) );
            time = time % (60 * 1000);
            s = Math.floor( time / 1000 );
            ms = time % 1000;

            newTime = pad(h, 2) + ':' + pad(m, 2) + ':' + pad(s, 2) + ':' + pad(ms, 3);
            return newTime;
        }

        function update() {
            div.innerHTML = "Time: " + formatTime(x.time());
        }

   		switch(id){
            case "start":
                clocktimer = setInterval(update, 1);
				x.start();
                break;
            case "stop":
                x.stop();
                clearInterval(clocktimer);
                break;
            case "reset":
                x.stop();
                x.reset();
                update();
                break;
            default:
                stop();
                break;
        }
	}
})

**Comment by moshekarmel1** [comment]
@shaikrizwan are you having this issue in a test file that you wrote yourself?

There is no `TestStopWatch.js` file...

If you're having issues, I would check this line `var h = m = s = ms = 0;`, which defines ms as a variable initialized to 0.

It also only exists inside the `formatTime` function. 

I hope that helps...

**Comment by shaikrizwan** [comment]
@moshekarmel1 
I have not Written any test file but i have named the class as TestStopwatch....
Yes there is No such class name as TestStopWatch.js.but I have used above js class in TestStopWatchController.js but it is showing the above following error. even there is no such class named as TestStopwatch.js..and i have used the above controller js class in component controller but not in application controller is that the write way to do it.if so i am unable to find why the error is coming.even i have tried the same code in different org same error is coming
error in diff org  when i clicked 
**on start :** 
Uncaught ReferenceError: ms is not defined
throws at components/c/StopWatch.js:63:32
**on stop:** 
This page has an error. You might just need to refresh it.
Action failed: c$StopWatch$controller$onClick [clocktimer is not defined]
Failing descriptor: {c$StopWatch$controller$onClick}
**on reset :** 
This page has an error. You might just need to refresh it.
Action failed: c$StopWatch$controller$onClick [ms is not defined]
Failing descriptor: {c$StopWatch$controller$onClick}

**Comment by carlosandthefifth** [comment]
@shaikrizwan 

I changed the variable initialization from:
           var h = m = s = ms = 0; 
to: 
            var h = 0;
            var m = 0;
            var s = 0;
            var ms = 0;
and I was able to get past the ms in not defined error
